
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BandServiceImplService", targetNamespace = "http://service.band.jaxws.java.patrikbergman.se/", wsdlLocation = "http://localhost:8888/bands?wsdl")
public class BandServiceImplService
    extends Service
{

    private final static URL BANDSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANDSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BANDSERVICEIMPLSERVICE_QNAME = new QName("http://service.band.jaxws.java.patrikbergman.se/", "BandServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/bands?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANDSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BANDSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BandServiceImplService() {
        super(__getWsdlLocation(), BANDSERVICEIMPLSERVICE_QNAME);
    }

    public BandServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANDSERVICEIMPLSERVICE_QNAME, features);
    }

    public BandServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BANDSERVICEIMPLSERVICE_QNAME);
    }

    public BandServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANDSERVICEIMPLSERVICE_QNAME, features);
    }

    public BandServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BandServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BandService
     */
    @WebEndpoint(name = "BandServiceImplPort")
    public BandService getBandServiceImplPort() {
        return super.getPort(new QName("http://service.band.jaxws.java.patrikbergman.se/", "BandServiceImplPort"), BandService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BandService
     */
    @WebEndpoint(name = "BandServiceImplPort")
    public BandService getBandServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.band.jaxws.java.patrikbergman.se/", "BandServiceImplPort"), BandService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANDSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BANDSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BANDSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
