
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BandService", targetNamespace = "http://api.band.java.patrikbergman.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BandService {


    /**
     * 
     * @param arg0
     * @return
     *     returns client.Band
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBand", targetNamespace = "http://api.band.java.patrikbergman.se/", className = "client.GetBand")
    @ResponseWrapper(localName = "getBandResponse", targetNamespace = "http://api.band.java.patrikbergman.se/", className = "client.GetBandResponse")
    @Action(input = "http://api.band.java.patrikbergman.se/BandService/getBandRequest", output = "http://api.band.java.patrikbergman.se/BandService/getBandResponse")
    public Band getBand(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
